env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {
  linebreak-style: ["error", "unix"],
  comma-dangle: ["error", "never"],
  arrow-body-style: ["error", "always"]
}
